services:
  main-service:
    build:
      context: ./
      dockerfile: ./main_service/Dockerfile
    restart: unless-stopped

  send-message-service:
    build:
       context: ./
       dockerfile: ./send_message_service/Dockerfile
    restart: unless-stopped

  autoend-service:
    build:
       context: ./
       dockerfile: ./autoend_service/Dockerfile
    restart: unless-stopped
    
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - ./uptime-kuma/data:/app/data
