name: Deploy to server

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Netbird Install
      run: |
        curl -fsSL https://pkgs.netbird.io/install.sh | sh
    - name: Netbird Connect
      run: |
        sudo netbird up --setup-key=${{ secrets.NETBIRD_SETUP_KEY }} --management-url=https://api.netbird.io:443
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd URA-project
          git fetch
          git pull
          docker compose down
          docker compose up -d --build