name: Deploy to server

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Netbird Connect
      run: |
        curl -fsSL https://pkgs.netbird.io/install.sh | sh
        sudo netbird up --setup-key=${{ secrets.NETBIRD_SETUP_KEY }} --hostname=urabot_github_deploy

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd urabot
          sh build.sh
